abcMarket/Models/ModelMetaData/Users.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace abcMarket.Models
{
    [MetadataType(typeof(UsersMetaData))]
    [Bind(Exclude = "varify_code,isvarify")]
    public partial class Users
    {
        [Display(Name = "驗證")]
        [NotMapped]
        public bool bool_isvarify { get; set; }
        private class UsersMetaData
        {
            [Key]
            [Display(Name = "記錄ID")]
            public int rowid { get; set; }          
            [Required(ErrorMessage = "姓名不可空白")]
            [DisplayFormat(ApplyFormatInEditMode = true, ConvertEmptyStringToNull = false, HtmlEncode = true, NullDisplayText = "請輸入姓名")]
            [Display(Name = "姓名")]
            public string mname { get; set; }
            [Required(ErrorMessage = "密碼不可空白")]
            [DataType(DataType.Password)]
            [DisplayFormat(ApplyFormatInEditMode = true, ConvertEmptyStringToNull = false, HtmlEncode = true)]
            [Display(Name = "密碼")]
            public string password { get; set; }
            [Required(ErrorMessage = "電子信箱不可空白")]
            [Display(Name = "電子信箱")]
            [DisplayFormat(ApplyFormatInEditMode = true, ConvertEmptyStringToNull = false, HtmlEncode = true, NullDisplayText = "請輸入電子信箱")]
            [EmailAddress(ErrorMessage = "請輸入電子信箱格式")]
            public string user_email { get; set; }          
            [Display(Name = "聯絡電話")]                 
            public string phone { get; set; }
            [Required(ErrorMessage = "角色不可空白")]
            [DisplayFormat(ApplyFormatInEditMode = true, ConvertEmptyStringToNull = false, HtmlEncode = true)]
            [Display(Name = "角色")]
            public string role_no { get; set; }
            [Display(Name = "出生日期")]
            [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
            public Nullable<System.DateTime> birthday { get; set; }
            [DisplayFormat(ApplyFormatInEditMode = true, ConvertEmptyStringToNull = false, HtmlEncode = true)]
            [Display(Name = "備註")]
            public string remark { get; set; }
            [Display(Name = "驗證碼")]
            public string varify_code { get; set; }
            [Display(Name = "驗證")]
            public Nullable<int> isvarify { get; set; }

        }
    }
}

abcMarket/Models/Users.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int rowid { get; set; }
        public string mname { get; set; }
        public string password { get; set; }
        public string user_email { get; set; }
        public string phone { get; set; }
        public string role_no { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string remark { get; set; }
        public string varify_code { get; set; }
        public Nullable<int> isvarify { get; set; }
    }
}

abcMarket/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using abcMarket.Models;
using System.Drawing;
using System.IO;
using System.Text;

namespace abcMarket.Controllers
{
    public class UserController : Controller
    {
        abcMarketEntities db = new abcMarketEntities();

        public ActionResult Login()
        {
            UserAccount.LogOut();
            cvmLogin model = new cvmLogin()
            {
                User_Email = "",
                Password = "",
                Remember = false
            };

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(cvmLogin model)
        {
            if (!ModelState.IsValid) return View(model);
            string str_password = model.Password;
            using (Cryptographys crpy = new Cryptographys())
            {
                str_password = crpy.SHA256Encode(str_password);
            }
            var users = db.Users
                .Where(m => m.user_email == model.User_Email)
                .Where(m => m.password == str_password)
                .FirstOrDefault();
            if (users == null)
            {
                ModelState.AddModelError("user_email", "登入帳號或密碼不符!!");
                return View(model);
            }

            UserAccount.Login(model.User_Email, users.mname, UserAccount.GetRoleNo(users.role_no));

            return RedirectToAction("RedirectToUserPage");
        }


        public ActionResult LogOut()
        {
            UserAccount.LogOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult ResetPassword()
        {
            cvmResetPassword model = new cvmResetPassword()
            {
                UserEmail = UserAccount.UserEmail,
                CurrentPassword = "",
                NewPassword = "",
                ConfirmPassword = ""
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult ResetPassword(cvmResetPassword model)
        {
            if (!ModelState.IsValid) return View(model);

            string str_password = "";
            using (Cryptographys cryp = new Cryptographys())
            { str_password = cryp.SHA256Encode(model.CurrentPassword); }
            bool bln_error = false;

            var check = db.Users
                .Where(m => m.user_email == model.UserEmail)
                .Where(m => m.password == str_password)
                .FirstOrDefault();

            if (check == null) { ModelState.AddModelError("CurrentPassword", "目前密碼輸入錯誤!!"); bln_error = true; }
            if (bln_error) return View(model);

            str_password = model.NewPassword;
            var user = db.Users.Where(m => m.user_email == model.UserEmail).FirstOrDefault();
            if (user != null)
            {
                //密碼加密
                using (Cryptographys cryp = new Cryptographys())
                { str_password = cryp.SHA256Encode(str_password); }

                user.password = str_password;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                db.Configuration.ValidateOnSaveEnabled = true;
            }
            return RedirectToAction("RedirectToUserPage");
        }
        public ActionResult RedirectToUserPage()
        {
            if (UserAccount.RoleNo == AppEnum.enUserRole.Admin) return RedirectToAction("Index", "Admin", new { area = "Admin" });
            //if (UserAccount.RoleNo == AppEnum.enUserRole.Member) return RedirectToAction("Index", "Member", new { area = "Member" });
            //if (UserAccount.RoleNo == AppEnum.enUserRole.Vendor) return RedirectToAction("Index", "Vendor", new { area = "Vendor" });
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            cvmRegister model = new cvmRegister();
            return View(model);
        }

        [HttpPost]
        public ActionResult Register(cvmRegister model)
        {
            if (!ModelState.IsValid) return View(model);

            //自定義檢查
            bool bln_error = false;
            var check = db.Users.Where(m => m.user_email == model.email).FirstOrDefault();
            if (check != null) { ModelState.AddModelError("", "電子信箱重覆註冊!"); bln_error = true; }
            if (bln_error) return View(model);

            //密碼加密
            using (Cryptographys cryp = new Cryptographys())
            {
                model.password = cryp.SHA256Encode(model.password);
                model.ConfirmPassword = model.password;
            }

            Users user = new Users();
            user.mname = model.mname;
            user.password = model.password;
            user.user_email = model.email;
            user.birthday = model.birthday;
            user.remark = model.remark;
            user.role_no = "Member";  //設定角色代號為 User
            user.varify_code = UserAccount.GetNewVarifyCode(); //產生驗證碼
            user.isvarify = 0;

            //寫入資料庫
            try
            {
                db.Configuration.ValidateOnSaveEnabled = false;
                db.Users.Add(user);
                db.SaveChanges();
                db.Configuration.ValidateOnSaveEnabled = true;
            }
            catch (Exception ex)
            {
                string str_message = ex.Message;
            }

            //寄出驗證信
            SendVerifyMail(model.email, user.varify_code);
            return RedirectToAction("SendEmailResult");
        }
        private string SendVerifyMail(string userEmail, string varifyCode)
        {
            string str_app_name = "abcMarket";
            var str_url = string.Format("/User/VerifyEmail/{0}", varifyCode);
            var str_link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, str_url);
            string str_subject = str_app_name + " - 帳號成功建立通知!!";
            string str_body = "<br/><br/>";
            str_body += "很高興告訴您，您的 " + str_app_name + " 帳戶已經成功建立. <br/>";
            str_body += "請按下下方連結完成驗證您的帳號程序!!<br/><br/>";
            str_body += "<a href='" + str_link + "'>" + str_link + "</a> ";
            str_body += "<br/><br/>";
            str_body += "本信件由電腦系統自動寄出,請勿回信!!<br/><br/>";
            str_body += string.Format("{0} 系統開發團隊敬上", str_app_name);

            using (GmailService gmail = new GmailService())
            {
                gmail.ReceiveEmail = userEmail;
                gmail.Subject = str_subject;
                gmail.Body = str_body;
                gmail.Send();
                return gmail.MessageText;
            }
        }
        [HttpGet]
        public ActionResult SendEmailResult()
        {
            return View();
        }

        [HttpGet]
        public ActionResult VerifyEmail(string id)
        {
            bool Status = false;
            db.Configuration.ValidateOnSaveEnabled = false;
            var user = db.Users.Where(m => m.varify_code == id).FirstOrDefault();
            if (user == null)
            { ViewBag.Message = "驗證碼錯誤!!"; }
            else
            {
                if (user.isvarify == 1)
                { ViewBag.Message = "此電子信箱已完成驗證, 請勿重覆執行!!"; }
                else
                {
                    user.isvarify = 1;
                    db.SaveChanges();
                    Status = true;
                }
            }
            ViewBag.Status = Status;
            return View();
        }
        [HttpGet]
        public ActionResult ForgetPassword()
        {
            cvmForgetPassword model = new cvmForgetPassword();
            return View(model);
        }
        [HttpPost]
        public ActionResult ForgetPassword(cvmForgetPassword model)
        {
            if (!ModelState.IsValid) return View(model);
            string code = model.code;
            if (code == TempData["code"].ToString())
            {
                SendForgetPasswordMail(model.user_email);
                return RedirectToAction("ForgetEmailResult");
            }
            else
            {
                ViewData["Message"] = "驗證碼錯誤!!";
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult ForgetEmailResult()
        {
            return View();
        }
        private string SendForgetPasswordMail(string userEmail)
        {
            string str_app_name = "abcMarket";
            var str_url = string.Format("/User/ResetForgetPassword");
            var str_link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, str_url);
            string str_subject = str_app_name + " - 密碼重設通知!!";
            string str_body = "";

            str_body += "很高興告訴您，您的 " + str_app_name + " 密碼重設要求已允許. <br/>";
            str_body += "請按下下方連結,重新設您的新密碼!!<br/><br/>";            
            str_body += "<a href='" + str_link + "'>" + str_link + "</a> ";
            str_body += "本信件由電腦系統自動寄出,請勿回信!!<br/><br/>";
            str_body += string.Format("{0} 系統開發團隊敬上", str_app_name);

            using (GmailService gmail = new GmailService())
            {
                gmail.ReceiveEmail = userEmail;
                gmail.Subject = str_subject;
                gmail.Body = str_body;
                gmail.Send();
                return gmail.MessageText;
            }
        }
        [HttpGet]
        public ActionResult ResetForgetPassword()
        {
            cvmResetForgetPassword model = new cvmResetForgetPassword()
            {
                user_email = UserAccount.UserEmail,
                NewPassword = "",
                ConfirmPassword = ""
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult ResetForgetPassword(cvmResetForgetPassword model)
        {
            if (!ModelState.IsValid) return View(model);

            string str_password = "";

abcMarket/Views/User/ForgetEmailResult.cshtml
@{
    ViewBag.Title = "ForgetEmailResult";
    Layout = "~/Views/Shared/_LayoutLite.cshtml";
}

<h2 style="color:white">密碼重設的信件已寄出, 請收信,並點擊信件重設密碼,謝謝!!</h2>

@Html.ActionLink("返回首頁", "Index", "Home", null, new { @class = "btn btn-success" })

abcMarket/Views/User/ForgetPassword.cshtml
@model cvmForgetPassword

@{
    ViewBag.Title = "ForgetPassword";
    Layout = "~/Views/Shared/_LayoutLite.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row row-cols-1 row-cols-md-1">
        <div class="forget">
            <h1 class="mb-4" id="title">忘記密碼</h1>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.user_email, htmlAttributes: new { @class = "form-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.user_email, new { htmlAttributes = new { @class = "form-control mb-4" } })
                    @Html.ValidationMessageFor(model => model.user_email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "form-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control mb-4" } })
                    <img id="code" src="/User/GetValidateCode/" class="mb-2"/>
                    @if (@ViewData["Message"] != null)
                    {
                        <span style="color:red;">
                            @ViewData["Message"]
                        </span>
                    }
                    @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
                </div>
                @*<input type="submit" value="登錄" class="btn btn-primary" style="border-radius: 10px; box-shadow: 3px 3px 10px rgba(50, 144, 233, 0.4);">*@
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <input type="submit" value="確定" class="btn btn-primary" />
                    @Html.ActionLink("返回登入", "Login", "User", null, new { @class = "btn btn-warning" })
                    @Html.ActionLink("返回首頁", "Index", "Home", null, new { @class = "btn btn-success" })
                </div>
            </div>

            @*<p>輸入的值 : </p>@ViewBag.code <br />
                <p>答案的值 : </p>@ViewBag.Ans<br />
                <p>驗證結果 : </p>@ViewBag.Result<br />*@

        </div>
    </div>
}

abcMarket/Views/User/Login.cshtml
@model cvmLogin

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<style>
    #demo_img {
        position: absolute;
        margin-top: -45px;
        margin-left: 25px;
        width: 20px;
        height: 20px;
    }
</style>

<div style="position:absolute;top:50%;left:50%;margin-left:-150px;margin-top:-200px;z-index:-50;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @*<form class="login mx-auto">*@
        <h1 style="text-align: center; margin: 50px;">登入Login</h1>
        <div class="mx-auto mb-2" style="text-align: center; color: rgba(39, 147, 236, 0.945);"><i class="fa fa-user-circle-o" style="font-size:100px;"></i></div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">E-mail</label>
            @*<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">*@
            @Html.TextBoxFor(model => model.User_Email, new { @class = "form-control", @style = "border-radius: 20px;" })
            @Html.ValidationMessageFor(model => model.User_Email, "", new { @class = "text-danger" })
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">密碼</label>
            @* <input type="password" class="form-control" id="exampleInputPassword1">*@
            @Html.TextBoxFor(model => model.Password, new { @class = "form-control", @style = "border-radius: 20px;", @type = "password", @id = "demo_input" })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            @*<input type="checkbox" onchange="document.getElementById('password').type = this.checked ? 'text' : 'password'">顯示密碼*@
        </div>

        <button type="submit" class="btn btn-primary mt-2" style="border-radius: 10px; box-shadow: 3px 3px 10px rgba(50, 144, 233, 0.4);">登入</button>
        <a href="/User/ForgetPassword" role="button" id="forget">忘記密碼?</a>
        @*<img id="demo_img" onclick="hideShowPsw()" src="@Url.Content("~/Images/app/Password/visible.svg")">*@
        @*</form>*@
    }
</div>


<div class="bg bg-blur"></div>

<script type="text/javascript">

    var demoImg = document.getElementById("demo_img");
    var demoInput = document.getElementById("demo_input");

    function hideShowPsw() {
        if (demoInput.type == "password") {
            demoInput.type = "text";
            demo_img.src = "@Url.Content("~/Images/app/Password/invisible.png")";
        } else {
            demoInput.type = "password";
            demo_img.src = "@Url.Content("~/Images/app/Password/visible.svg")";
        }
    }
</script>

abcMarket/Views/User/Login_goshopping.cshtml
@model cvmLogin

@{
    ViewBag.Title = "會員登入";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal" style="margin-top:20px">
        <h4 style="text-align:center;">登入 ABC 線上商城會員</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.User_Email, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.User_Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <div class="checkbox">
                    @Html.LabelFor(model => model.Remember, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Remember)
                    @Html.ValidationMessageFor(model => model.Remember, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="登入系統" class="btn btn-primary" />
                @Html.ActionLink("註冊帳號", "Create", "User", null, new { @class = "btn btn-info" })
                @Html.ActionLink("返回首頁", "Index", "Home", null, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

abcMarket/Views/User/Register.cshtml
@model cvmRegister

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_LayoutLite.cshtml";
}

<style>
    body {
        padding: 0;
    }
</style>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row row-cols-1 row-cols-md-1">
        <div class="forget" style="margin-top:-280px;">
            <h1 class="mb-2" id="title" style="text-align:left">會員註冊</h1>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            @Html.LabelFor(model => model.mname, htmlAttributes: new { @class = "form-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.mname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mname, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "form-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "form-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "form-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.birthday, htmlAttributes: new { @class = "form-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.birthday, new { htmlAttributes = new { @class = "form-control datepicker", @PlaceHolder = "yyyy/mm/dd" } })
                @Html.ValidationMessageFor(model => model.birthday, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "form-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-12 mt-2">
                <input type="submit" value="註冊" class="btn btn-primary" />
                @Html.ActionLink("返回登入", "Login", "User", null, new { @class = "btn btn-warning" })
                @Html.ActionLink("返回首頁", "Index", "Home", null, new { @class = "btn btn-success" })
            </div>

        </div>
    </div>
}

@section scripts {
    <script type="text/javascript">
        $(function () {
            $('#mno').focus();
            $('#birthday').datepicker({
                changeMonth: true,
                changeYear: true,
                format: "yyyy/mm/dd",
                language: "zh-TW"
            });
        });
    </script>
}

abcMarket/Views/User/ResetForgetPassword.cshtml
@model cvmResetForgetPassword

@{
    ViewBag.Title = "ResetForgetPassword";
    Layout = "~/Views/Shared/_LayoutLite.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row row-cols-1 row-cols-md-1">
        <div class="forget">
            <h3 class="mb-4" id="title">忘記密碼-重設密碼</h3>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.user_email, htmlAttributes: new { @class = "form-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.user_email, new { htmlAttributes = new { @class = "form-control mb-4" } })
                    @Html.ValidationMessageFor(model => model.user_email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "form-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control mb-4" } })
                    @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "form-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control mb-4" } })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="存檔" class="btn btn-success" onclick="alert('已變更密碼,下次登入請使用新密碼!!')" />
                    @Html.ActionLink("返回", "RedirectToUserPage", "User", null, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    </div>
}

abcMarket/Views/User/ResetPassword.cshtml
@model cvmResetPassword

@{
    ViewBag.Title = "ResetPassword";
    Layout = "~/Views/Shared/_LayoutLite.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.UserEmail)
    <div class="form-horizontal">
        <h4 class="text-center">修改密碼</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CurrentPassword, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.CurrentPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="存檔" class="btn btn-success" />
                @Html.ActionLink("返回", "RedirectToUserPage", "User", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

abcMarket/Views/User/SendEmailResult.cshtml
@{
    ViewBag.Title = "SendEmailResult";
    Layout = "~/Views/Shared/_LayoutLite.cshtml";
}

<h2 style="color:white">會員申請的信件已寄出, 請收信,並點擊驗證信件功能,謝謝!!</h2>

@Html.ActionLink("返回首頁", "Index", "Home", null, new { @class = "btn btn-success" })

abcMarket/Views/User/VerifyEmail.cshtml
@{
    ViewBag.Title = "VerifyEmail";
    Layout = "~/Views/Shared/_LayoutLite.cshtml";
}

@if (ViewBag.Status)
{
    <h2 style="color:white">恭喜你, 已經完成會員帳號驗證, 請重新登入!!</h2>  
}
else
{
    <p>@ViewBag.Message</p>
}

@Html.ActionLink("返回首頁", "Index", "Home", null, new { @class = "btn btn-success" })