abcMarket/Models/ModelMetaData/Propertys.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace abcMarket.Models
{
    [MetadataType(typeof(PropertysMetaData))]
    public partial class Propertys
    {
        private class PropertysMetaData
        {
            [Key]
            [Display(Name = "記錄ID")]
            public int rowid { get; set; }
            [Display(Name = "屬性編號")]
            [DisplayFormat(ConvertEmptyStringToNull = false, HtmlEncode = true, NullDisplayText = "請輸入屬性編號")]
            [Required(ErrorMessage = "屬性編號不可空白")]
            public string mno { get; set; }
            [Display(Name = "屬性名稱")]
            [DisplayFormat(ConvertEmptyStringToNull = false, HtmlEncode = true, NullDisplayText = "請輸入屬性名稱")]
            [Required(ErrorMessage = "屬性名稱不可空白")]
            public string mname { get; set; }
            [Display(Name = "屬性值")]
            [DisplayFormat(ConvertEmptyStringToNull = false, HtmlEncode = true, NullDisplayText = "請輸入屬性值")]
            [Required(ErrorMessage = "屬性值不可空白")]
            public string mvalue { get; set; }
            [Display(Name = "備註")]
            [DisplayFormat(ConvertEmptyStringToNull = false, HtmlEncode = true, NullDisplayText = "請輸入備註")]
            public string remark { get; set; }
        }
    }
}

abcMarket/Models/Propertys.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propertys
    {
        public int rowid { get; set; }
        public string mno { get; set; }
        public string mname { get; set; }
        public string mvalue { get; set; }
        public string remark { get; set; }
    }
}

abcMarket/Areas/Admin/Controllers/PropertysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using abcMarket.Models;

namespace abcMarket.Areas.Admin.Controllers
{
    public class PropertysController : Controller
    {
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetDataList()
        {
            using (abcMarketEntities db = new abcMarketEntities())
            {
                var models = db.Propertys.OrderBy(m => m.mno).ToList();
                return Json(new { data = models }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult Edit(int id = 0)
        {
            using (abcMarketEntities db = new abcMarketEntities())
            {
                if (id == 0)
                {
                    Propertys new_model = new Propertys();
                    return View(new_model);
                }
                var models = db.Propertys.Where(m => m.rowid == id).FirstOrDefault();
                return View(models);
            }
        }

        [HttpPost]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult Edit(Propertys models)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                using (abcMarketEntities db = new abcMarketEntities())
                {
                    if (models.rowid > 0)
                    {
                        //Edit 
                        var propertys = db.Propertys.Where(m => m.rowid == models.rowid).FirstOrDefault();
                        if (propertys != null)
                        {
                            propertys.mno = models.mno;
                            propertys.mname = models.mname;
                            propertys.remark = models.remark;
                        }
                    }
                    else
                    {
                        //Save
                        db.Propertys.Add(models);
                    }
                    db.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpGet]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult Delete(int id)
        {
            using (abcMarketEntities db = new abcMarketEntities())
            {
                var model = db.Propertys.Where(m => m.rowid == id).FirstOrDefault();
                if (model != null)
                {
                    return View(model);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult DeleteData(int id)
        {
            bool status = false;
            using (abcMarketEntities db = new abcMarketEntities())
            {
                var model = db.Propertys.Where(m => m.rowid == id).FirstOrDefault();
                if (model != null)
                {
                    db.Propertys.Remove(model);
                    db.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }
    }
}

abcMarket/Areas/Admin/Views/Propertys/Delete.cshtml
@model abcMarket.Models.Propertys

@{
    ViewBag.Title = "商品屬性刪除";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}

@using (Html.BeginForm("Delete", "Propertys", new { area = "Admin" }, FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(model => model.rowid)

    <div class="form-group">
        @Html.LabelFor(model => model.mno, htmlAttributes: new { @class = "control-label control-header" })
        @Html.Label("：", htmlAttributes: new { @class = "control-label control-header" })
        @if (Model.mno != null)
        {<span class="control-label control-value">@Model.mno</span>}
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.mname, htmlAttributes: new { @class = "control-label control-header" })
        @Html.Label("：", htmlAttributes: new { @class = "control-label control-header" })
        @if (Model.mname != null)
        {<span class="control-label control-value">@Model.mname</span>}
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.mvalue, htmlAttributes: new { @class = "control-label control-header" })
        @Html.Label("：", htmlAttributes: new { @class = "control-label control-header" })
        @if (Model.mvalue != null)
        {<span class="control-label control-value">@Model.mvalue</span>}
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label control-header" })
        @Html.Label("：", htmlAttributes: new { @class = "control-label control-header" })
        @if (Model.remark != null)
        {<span class="control-label control-value">@Model.remark</span>}
    </div>

    <div>
        <input type="submit" value="刪除" class="btn btn-danger form-button" />
    </div>
}

abcMarket/Areas/Admin/Views/Propertys/Edit.cshtml
@model abcMarket.Models.Propertys

@{
    ViewBag.Title = "商品屬性" + ((Model.rowid > 0) ? "修改" : "新增");
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}

@using (Html.BeginForm("Edit", "Propertys", new { area = "Admin" }, FormMethod.Post, new { id = "popupForm" }))
{
    @Html.AntiForgeryToken()
    if (Model != null && Model.rowid > 0)
    {
        @Html.HiddenFor(model => model.rowid)
    }

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.mno, htmlAttributes: new { @class = "control-label control-header" })
        @Html.TextBoxFor(model => model.mno, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.mno)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.mname, htmlAttributes: new { @class = "control-label control-header" })
        @Html.TextBoxFor(model => model.mname, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.mname)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.mvalue, htmlAttributes: new { @class = "control-label control-header" })
        @Html.TextBoxFor(model => model.mvalue, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.mvalue)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label control-header" })
        @Html.TextBoxFor(model => model.remark, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.remark)
    </div>

    <div>
        <input type="submit" value="存檔" class="btn btn-success form-button" />
    </div>
}

abcMarket/Areas/Admin/Views/Propertys/Index.cshtml
@{
    ViewBag.Title = "基本資料管理 / 屬性資料設定";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

<div style="width:100%; margin:0 auto" class="tablecontainer">
    <table id="DatatableList" class="table table-bordered  display dt-responsive nowrap">
        <thead>
            <tr>
                <th>
                    <a class="popup" title="新增記錄" href="/Admin/Propertys/Edit/0"><i class="fas fa-plus fa-2x"></i></a>
                </th>
                <th>編號</th>
                <th>名稱</th>
                <th title="以逗號(,)為不同名稱的分隔符號">屬性值</th>
                <th>備註</th>
            </tr>
        </thead>
    </table>
</div>

<script src="@Url.Content("~/Scripts/apps/admin/propertys_index.js")"></script>