abcMarket/Areas/Admin/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using abcMarket.Models;

namespace abcMarket.Areas.Admin.Controllers
{
    public class MemberController : Controller
    {
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult Index(int id = 2)
        {
            UserAccount.UserRoleNo = "Member";
            UserAccount.UserStatus = id;
            return View();
        }
        public ActionResult GetDataList()
        {
            using (abcMarketEntities db = new abcMarketEntities())
            {
                if (UserAccount.UserStatus == 2)
                {
                    // 全部會員資料
                    var all_users = db.Users
                    .Where(m => m.role_no == UserAccount.UserRoleNo)
                    .OrderBy(m => m.user_email).ToList();
                    return Json(new { data = all_users }, JsonRequestBehavior.AllowGet);
                }

                // 已審核/未審核會員資料
                var models = db.Users
                .Where(m => m.role_no == UserAccount.UserRoleNo)
                .Where(m => m.isvarify == UserAccount.UserStatus)
                .OrderBy(m => m.user_email).ToList();
                return Json(new { data = models }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult Edit(int id = 0)
        {
            using (abcMarketEntities db = new abcMarketEntities())
            {
                if (id == 0)
                {
                    Users new_model = new Users();
                    new_model.role_no = UserAccount.UserRoleNo;
                    if (UserAccount.UserStatus == 0)
                    { new_model.isvarify = 0; new_model.bool_isvarify = false; }
                    else
                    { new_model.isvarify = 1; new_model.bool_isvarify = true; }
                    return View(new_model);
                }
                var models = db.Users.Where(m => m.rowid == id).FirstOrDefault();
                models.bool_isvarify = Shop.IntegerToBool(models.isvarify);
                return View(models);
            }
        }
        [HttpPost]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult Edit(Users models)
        {
            bool status = false;
            ModelState.Remove("Password"); //忽略 Password 驗證
            ModelState.Remove("role_no"); //忽略 role_no 驗證
            if (ModelState.IsValid)
            {
                using (abcMarketEntities db = new abcMarketEntities())
                {
                    if (models.rowid > 0)
                    {
                        //Edit 
                        var users = db.Users.Where(m => m.rowid == models.rowid).FirstOrDefault();
                        if (users != null)
                        {
                            users.isvarify = Shop.BoolToInteger(models.bool_isvarify);
                            //users.mno = models.mno;
                            users.mname = models.mname;
                            users.user_email = models.user_email;
                            users.birthday = models.birthday;
                            users.remark = models.remark;
                        }
                    }
                    else
                    {
                        //Save
                        models.role_no = UserAccount.UserRoleNo;
                        models.varify_code = UserAccount.GetNewVarifyCode(); //產生驗證碼
                        if (UserAccount.UserStatus < 2)
                            models.isvarify = UserAccount.UserStatus;
                        else
                            models.isvarify = Shop.BoolToInteger(models.bool_isvarify);

                        db.Users.Add(models);
                    }
                    try
                    {
                        db.Configuration.ValidateOnSaveEnabled = false;
                        db.SaveChanges();
                        db.Configuration.ValidateOnSaveEnabled = true;
                        status = true;
                    }
                    catch (Exception ex)
                    {
                        string str_message = ex.Message;
                        status = false;
                    }
                }
            }
            return new JsonResult { Data = new { status = status } };
        }
        [HttpGet]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult Delete(int id)
        {
            using (abcMarketEntities db = new abcMarketEntities())
            {
                var model = db.Users.Where(m => m.rowid == id).FirstOrDefault();
                if (model != null)
                {
                    model.bool_isvarify = Shop.IntegerToBool(model.isvarify);
                    return View(model);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult DeleteData(int id)
        {
            bool status = false;
            using (abcMarketEntities db = new abcMarketEntities())
            {
                var model = db.Users.Where(m => m.rowid == id).FirstOrDefault();
                if (model != null)
                {

                    db.Users.Remove(model);
                    db.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpGet]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult Reset(int id)
        {
            using (abcMarketEntities db = new abcMarketEntities())
            {
                var model = db.Users.Where(m => m.rowid == id).FirstOrDefault();
                if (model != null)
                {
                    model.bool_isvarify = Shop.IntegerToBool(model.isvarify);
                    return View(model);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }

        [HttpPost]
        [ActionName("Reset")]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult ResetPassword(int id)
        {
            bool status = false;
            using (abcMarketEntities db = new abcMarketEntities())
            {
                var model = db.Users.Where(m => m.rowid == id).FirstOrDefault();
                if (model != null)
                {
                    using (Cryptographys crpy = new Cryptographys())
                    {
                        model.password = crpy.SHA256Encode(model.user_email);
                        db.SaveChanges();
                    }
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpGet]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult Confirm(int id)
        {
            using (abcMarketEntities db = new abcMarketEntities())
            {
                var model = db.Users.Where(m => m.rowid == id).FirstOrDefault();
                if (model != null)
                {
                    model.isvarify = 1;
                    db.SaveChanges();
                    return RedirectToAction("Index", "Member", new { area = "Admin", id = UserAccount.UserStatus });
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }

        [HttpGet]
        [LoginAuthorize(RoleNo = "Admin")]
        public ActionResult UnConfirm(int id = 0)
        {
            using (abcMarketEntities db = new abcMarketEntities())
            {
                var model = db.Users.Where(m => m.rowid == id).FirstOrDefault();
                if (model != null)
                {
                    model.isvarify = 0;
                    db.SaveChanges();
                    return RedirectToAction("Index", "Member", new { area = "Admin", id = UserAccount.UserStatus });
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }
    }
}

abcMarket/Areas/Member/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using abcMarket.Models;

namespace abcMarket.Areas.Member.Controllers
{
    public class MemberController : Controller
    {
        [LoginAuthorize(RoleNo = "Member")]
        public ActionResult Index()
        {
            UserAccount.UploadImageMode = false;
            using (Sale sale = new Sale(DateTime.Today))
            {
                sale.CountAmount("M");
                ViewBag.MonthAmount = sale.AmountData;
                ViewBag.MonthAmountPercent = sale.PercentData;

                sale.CountQty("M");
                ViewBag.MonthCount = sale.AmountData; ;
                ViewBag.MonthCountPercent = sale.PercentData;

                sale.CountAmount("Y");
                ViewBag.YearAmount = sale.AmountData;
                ViewBag.YearAmountPercent = sale.PercentData;

                sale.CountQty("Y");
                ViewBag.YearCount = sale.AmountData; ;
                ViewBag.YearCountPercent = sale.PercentData;

                List<string> arrYearMonthName = sale.GetYearMonthNameList();
                List<int> arrYearMonthAmount = sale.GetYearMonthAmountList("Base");
                ViewBag.BaseYearAmountRank = sale.GetSaleRank("Base", "Amount", 20);
                ViewBag.BaseYearQtyRank = sale.GetSaleRank("Base", "Qty", 20);
                ViewBag.BaseYearMonthName = Newtonsoft.Json.JsonConvert.SerializeObject(arrYearMonthName);
                ViewBag.BaseYearMonthAmount = Newtonsoft.Json.JsonConvert.SerializeObject(arrYearMonthAmount);

                sale.CountAmount("W");
                List<string> arrPriorWeekName = sale.GetWeekNameList("Prior");
                List<int> arrPriorWeekAmount = sale.GetWeekAmountList("Prior");
                ViewBag.PriorWeekName = Newtonsoft.Json.JsonConvert.SerializeObject(arrPriorWeekName);
                ViewBag.PriorWeekAmount = Newtonsoft.Json.JsonConvert.SerializeObject(arrPriorWeekAmount);

                List<string> arrBaseWeekName = sale.GetWeekNameList("Base");
                List<int> arrBaseWeekAmount = sale.GetWeekAmountList("Base");
                ViewBag.BaseWeekName = Newtonsoft.Json.JsonConvert.SerializeObject(arrBaseWeekName);
                ViewBag.BaseWeekAmount = Newtonsoft.Json.JsonConvert.SerializeObject(arrBaseWeekAmount);

                return View();
            }
        }
        [LoginAuthorize(RoleNo = "Member")]
        public ActionResult MemberProfile()
        {
            using ( abcMarketEntities db = new abcMarketEntities())
            {
                var model = db.Users
                    .Where(m => m.user_email == UserAccount.UserEmail)
                    .FirstOrDefault();
                return View(model);
            }
        }
        [HttpGet]
        [LoginAuthorize(RoleNo = "Member")]
        public ActionResult EditProfile()
        {
            using (abcMarketEntities db = new abcMarketEntities())
            {
                var model = db.Users
                .Where(m => m.user_email == UserAccount.UserEmail)
                .FirstOrDefault();
                return View(model);
            }
        }
        [HttpPost]
        [LoginAuthorize(RoleNo = "Member")]
        public ActionResult EditProfile(Users model)
        {
            if (!ModelState.IsValid) return View(model);

            using (abcMarketEntities db = new abcMarketEntities())
            {
                var user = db.Users
                .Where(m => m.rowid == model.rowid)
                .FirstOrDefault();

                if (user != null)
                {
                    user.mname = model.mname;
                    user.phone = model.phone;
                    user.user_email = model.user_email;
                    user.birthday = model.birthday;
                    user.remark = model.remark;
                    db.SaveChanges();
                }

                return RedirectToAction("MemberProfile");
            }
        }
        [LoginAuthorize(RoleNo = "Member")]
        public ActionResult UploadImage()
        {
            UserAccount.UploadImageMode = true;
            ImageService.ImageTitle = String.Format("{0}{1}會員圖片上傳", UserAccount.UserEmail, UserAccount.UserName);
            ImageService.ImageFolder = "~/Images";
            ImageService.ImageSubFolder = "Member";
            ImageService.ImageName = UserAccount.UserEmail;
            ImageService.ImageExtention = "jpg";
            ImageService.UploadImageMode = true;
            return RedirectToAction("MemberProfile");
        }

        //[HttpPost]
        //[LoginAuthorize(RoleNo = "Member")]
        //public ActionResult Upload(HttpPostedFileBase file)
        //{
        //    if (file != null)
        //    {
        //        if (file.ContentLength > 0)
        //        {
        //            var fileName = UserAccount.UserEmail + ".jpg";
        //            var path = Path.Combine(Server.MapPath("~/Images/user"), fileName);
        //            if (System.IO.File.Exists(path)) System.IO.File.Delete(path);
        //            file.SaveAs(path);
        //        }
        //    }
        //    UserAccount.UploadImageMode = false;
        //    return RedirectToAction("MemberProfile");
        //}

        //[LoginAuthorize(RoleNo = "Member")]
        //public ActionResult UploadCancel()
        //{
        //    UserAccount.UploadImageMode = false;
        //    return RedirectToAction("MemberProfile");
        //}
    }
}

abcMarket/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace abcMarket.Controllers
{
    public class ImageController : Controller
    {
        [LoginAuthorize()]
        public ActionResult UploadImage()
        {
            return View();
        }

        [LoginAuthorize()]
        [HttpPost]
        public ActionResult Uploadimage(HttpPostedFileBase file)
        {
            ImageService.UserUploadimage(file);
            if (!string.IsNullOrEmpty(ImageService.ReturnAreaName))
                return RedirectToAction(ImageService.ReturnActionName, ImageService.ReturnControllerName, new { area = ImageService.ReturnAreaName });
            return RedirectToAction(ImageService.ReturnActionName, ImageService.ReturnControllerName);
        }

    }
}

abcMarket/Areas/Member/Views/Member/EditProfile.cshtml
@model abcMarket.Models.Users

@{
    ViewBag.Title = "帳號資料管理 / 帳號資料修改";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.rowid)
    @Html.HiddenFor(model => model.password)
    @Html.HiddenFor(model => model.role_no)
    @Html.HiddenFor(model => model.varify_code)
    @Html.HiddenFor(model => model.isvarify)

    <div class="form-group">
        @Html.LabelFor(model => model.mname, htmlAttributes: new { @class = "control-label control-header col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.user_email, htmlAttributes: new { @class = "control-label control-header col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.user_email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.user_email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label control-header col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.birthday, htmlAttributes: new { @class = "control-label control-header col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.birthday, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.birthday, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label control-header col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="存檔" class="btn btn-success form-button" />
        </div>
    </div>
</div>
}

<script src="@Url.Content("~/Scripts/apps/datepicker.js")"></script>

abcMarket/Areas/Member/Views/Member/MemberProfile.cshtml
@model abcMarket.Models.Users

@{
    ViewBag.Title = "帳號資料管理 / 帳號明細";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

<link href="@Url.Content("~/Content/FileUpload.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/FileUpload.js")"></script>


@if (!UserAccount.UploadImageMode)
{
    <div>
        <div class="row">
            <div class="col-2">
                <img src="@Url.Content(@UserAccount.UserImageUrl)" class="user-profile-image" />
            </div>
            <div class="col-10">

                <div class="row">
                    <div class="col-12 control-label control-header">
                        <span class="control-caption">@Html.DisplayNameFor(m => m.mname)：</span>@Html.DisplayFor(m => m.mname)
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 control-label control-header">
                        <span class="control-caption">@Html.DisplayNameFor(m => m.phone)：</span>@Html.DisplayFor(m => m.phone)
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 control-label control-header">
                        <span class="control-caption">@Html.DisplayNameFor(m => m.user_email)：</span>@Html.DisplayFor(m => m.user_email)
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 control-label control-header">
                        <span class="control-caption">@Html.DisplayNameFor(m => m.birthday)：</span>@Html.DisplayFor(m => m.birthday)
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 control-label control-header">
                        <span class="control-caption">@Html.DisplayNameFor(m => m.remark)：</span>@Html.DisplayFor(m => m.remark)
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <p>
            @Html.ActionLink("編輯帳號", "EditProfile", "Member", new { area = "Member" }, new { @class = "btn btn-success form-button" })
            @Html.ActionLink("上傳圖像", "UploadImage", "Member", new { area = "Member" }, new { @class = "btn btn-success form-button" })
        </p>
    </div>
}
else
{
    <div class="file-upload">
        @using (Html.BeginForm("Uploadimage", "Image", new { area = "" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="text-center">
                    <h3>@ImageService.ImageTitle</h3>
                </div>
            </div>
            <div class="image-upload-wrap">
                <input type="file" name="file" id="file" class="form-control file-upload-input" onchange="readURL(this);" accept="image/*" />
                <div class="drag-text">
                    <h3>選擇圖片</h3>
                </div>
            </div>
            <div class="file-upload-content">
                <img class="file-upload-image" src="#" alt="your image" />
                <div class="image-title-wrap">
                    <button type="button" onclick="removeUpload()" class="remove-image">移除 <span class="image-title">上傳圖片</span></button>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col-md-12 text-center">
                    <input type="submit" value="上傳檔案" class="btn btn-primary" />
                    @if (!string.IsNullOrEmpty(ImageService.ReturnAreaName))
                    {
                        @Html.ActionLink("取消上傳", ImageService.ReturnActionName, ImageService.ReturnControllerName, new { area = ImageService.ReturnAreaName }, new { @class = "btn btn-danger" })
                    }
                    else
                    {
                        UserAccount.UploadImageMode = false;
                        @Html.ActionLink("取消上傳", "MemberProfile", "Member", new { area = "Member" }, new { @class = "btn btn-danger" })
                    }
                </div>
            </div>
        }

    </div>
}